version: '3'

volumes:
  dbdata: { }

services:
  postgres:
    image: postgres:13-alpine
    container_name: portal-postgres
    env_file: envs/.env
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    image: portal_django
    container_name: portal-django
    volumes:
      - .:/src
    depends_on:
      - postgres
    env_file: envs/.env
    ports:
      - "8000:8000"
    command: /start

