# Generated by Django 3.2.5 on 2021-07-13 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='', max_length=25)),
                ('date_of_interview', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('interviewed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews_from', to=settings.AUTH_USER_MODEL, verbose_name='Interviewed')),
                ('interviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews_to', to=settings.AUTH_USER_MODEL, verbose_name='Interviewer')),
            ],
            options={
                'unique_together': {('interviewer', 'interviewed')},
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_grade', models.CharField(choices=[('UNDEFINED', 'Undefined'), ('JUNIOR', 'Junior'), ('MIDDLE', 'Middle'), ('SENIOR', 'Senior')], max_length=30)),
                ('response', models.TextField()),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interview')),
            ],
        ),
    ]
