# Generated by Django 3.2.5 on 2021-07-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interview',
            unique_together=set(),
        ),
    ]
