# Generated by Django 3.2.5 on 2021-07-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_alter_interview_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date_of_interview',
            field=models.DateTimeField(null=True),
        ),
    ]
