# Generated by Django 3.2.5 on 2021-07-29 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0004_auto_20210729_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interviewed',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews_from', to=settings.AUTH_USER_MODEL, verbose_name='Interviewed'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interviewer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews_to', to=settings.AUTH_USER_MODEL, verbose_name='Interviewer'),
        ),
    ]
